processor.py

feat: 支持全并行下载

---

.github/workflows/docker-image-debug.yml
.github/workflows/docker-image.yml

fix https://github.com/amtoaer/bili-sync/pull/15

fix: docker meta username error

---

.github/workflows/docker-image-debug.yml
.github/workflows/docker-image.yml
Dockerfile
README.md

1. Docker镜像构建流程增加缓存
2. Alpine升级3.19
3. Dockerfile内增加VOLUME提示
4. 设置容器内LANG为 `zh_CN.UTF-8`
5. 使用 `tini` 防止僵尸进程 & 传递系统信号量
6. 修复DockerHub文档图片无法显示

Optimization docker

---

commands.py
constants.py
credential.py
entry.py
migrations/models/4_20240224020723_update.py
models.py
nfo.py
processor.py
pyproject.toml
settings.py
utils.py

feat: 支持分 p 视频下载

---

Cargo.lock
Cargo.toml
README.md
src/bilibili/client.rs
src/bilibili/credential.rs
src/bilibili/favorite_list.rs
src/config.rs
src/core/command.rs
src/core/utils.rs
src/database.rs
src/lib.rs
src/main.rs

refactor: 用更 idiomatic 的方式改写一些代码

---

src/main.rs

chore: 设置默认日志等级为 info

---

Cargo.lock
Cargo.toml
src/bilibili/client.rs
src/core/command.rs

1. 修正了对风控的判断，将风控错误正常传播到上层
2. 为请求加入连接和读取超时，避免无限阻塞
还没测试，等回家测试没问题再合

fix: 尝试修复风控判断错误，以及可能的阻塞问题

---

src/database.rs

feat: 放宽数据库连接池的连接数和获取时间，避免 time out 错误

---

Cargo.lock
Cargo.toml
crates/bili_sync/Cargo.toml
crates/bili_sync/src/config.rs
crates/bili_sync/src/core/command.rs
crates/bili_sync/src/core/utils.rs
crates/bili_sync/src/main.rs

refactor: 引入 clap 处理环境变量和命令行参数

---

crates/bili_sync/src/adapter/collection.rs
crates/bili_sync/src/adapter/favorite.rs
crates/bili_sync/src/adapter/watch_later.rs
crates/bili_sync/src/bilibili/collection.rs
crates/bili_sync/src/config.rs
crates/bili_sync/src/main.rs
crates/bili_sync/src/utils/mod.rs
crates/bili_sync/src/workflow.rs

有反馈说支持 wbi 签名后仍然可能出现风控问题，因此引入一个 delay 配置，方便自定义各类任务的执行间隔。

feat: 支持各种任务结束之后的 delay 配置

---

crates/bili_sync/src/adapter/collection.rs
crates/bili_sync/src/adapter/favorite.rs
crates/bili_sync/src/adapter/mod.rs
crates/bili_sync/src/adapter/submission.rs
crates/bili_sync/src/adapter/watch_later.rs
crates/bili_sync/src/bilibili/collection.rs
crates/bili_sync/src/bilibili/favorite_list.rs
crates/bili_sync/src/bilibili/mod.rs
crates/bili_sync/src/bilibili/submission.rs
crates/bili_sync/src/bilibili/watch_later.rs
crates/bili_sync/src/workflow.rs

结合之前的 https://github.com/amtoaer/bili-sync/pull/228 应该能规避一些错误。

feat: 确保 video stream 在出现错误时返回 Err

---

Cargo.lock
Cargo.toml
crates/bili_sync/Cargo.toml
crates/bili_sync/src/adapter/collection.rs
crates/bili_sync/src/adapter/favorite.rs
crates/bili_sync/src/adapter/mod.rs
crates/bili_sync/src/adapter/submission.rs
crates/bili_sync/src/adapter/watch_later.rs
crates/bili_sync/src/utils/model.rs
crates/bili_sync/src/workflow.rs

refactor: 引入 enum_dispatch 静态分发，提升性能

---

crates/bili_sync/src/bilibili/mod.rs
crates/bili_sync/src/bilibili/subtitle.rs
crates/bili_sync/src/bilibili/video.rs
crates/bili_sync/src/utils/status.rs
crates/bili_sync/src/workflow.rs

b 站接口也太夸张了，`x/player/v2` 不带签名的接口几秒之内只会返回一次正确结果，剩下的全是随机生成的 AI 字幕；只有用 `x/player/wbi/v2` 才能正常返回。

feat: 支持下载 cc 字幕

---

crates/bili_sync/src/adapter/collection.rs
crates/bili_sync/src/adapter/favorite.rs
crates/bili_sync/src/adapter/mod.rs
crates/bili_sync/src/adapter/submission.rs
crates/bili_sync/src/adapter/watch_later.rs
crates/bili_sync/src/main.rs
crates/bili_sync/src/workflow.rs

更加充分地利用 tokio 多 worker 线程，应该会带来性能提升

chore: 使用 tokio::spawn 运行主任务

---

crates/bili_sync/src/workflow.rs

之前写法感觉没太大必要，代价较大还会导致 up 主信息无法更新。
直接用 HashSet 从外层确保单个 up 主的信息只会被单个任务处理，节省开销的同时还能确保后续出现新视频能更新该 up 主的信息。

chore: 简化 up 主处理逻辑，支持 up 主信息更新

---

crates/bili_sync/src/utils/status.rs
crates/bili_sync/src/workflow.rs

顺便支持了 status 和 [u32;N] 的转换，后面应该会用到。

refactor: 使用 const 泛型约束 status

---

crates/bili_sync/src/workflow.rs

fix: 修改拼写错误 seprate -> separate

---

crates/bili_sync/src/utils/status.rs

比如新引入了字幕下载，由于标记位未改变所以默认不会触发。用户可以手动重置某个视频来触发新的字幕下载任务。

feat: reset_failed 支持修正标记位，这允许用户手动触发新的子任务

---

crates/bili_sync/src/bilibili/analyzer.rs
crates/bili_sync/src/bilibili/mod.rs
crates/bili_sync/src/config/global.rs

fix: 改进视频流编码判断逻辑

---

crates/bili_sync/src/downloader.rs

fix: 修复杜比视界合并后变为普通 HDR 的错误

---

crates/bili_sync/src/bilibili/video.rs

看了看 video 用到的这些接口，都是支持 bvid 参数的，没必要多余做一次转换。

refactor: 移除无意义的 bvid 转 aid 逻辑

---

crates/bili_sync/src/workflow.rs

refactor: 优化填充视频详情时的性能

---

crates/bili_sync/src/api/handler.rs
crates/bili_sync/src/api/request.rs
crates/bili_sync/src/api/response.rs
crates/bili_sync/src/bilibili/collection.rs
crates/bili_sync/src/bilibili/me.rs
crates/bili_sync/src/bilibili/mod.rs
crates/bili_sync/src/main.rs
crates/bili_sync/src/task/http_server.rs
crates/bili_sync/src/task/video_downloader.rs
crates/bili_sync/src/utils/validation.rs
web/src/app.css
web/src/lib/api.ts
web/src/lib/components/app-sidebar.svelte
web/src/lib/components/subscription-card.svelte
web/src/lib/components/subscription-dialog.svelte
web/src/lib/types.ts
web/src/routes/+layout.ts
web/src/routes/me/collections/+page.svelte
web/src/routes/me/favorites/+page.svelte
web/src/routes/me/uppers/+page.svelte
web/src/routes/video/[id]/+page.svelte
web/src/routes/video/[id]/+page.ts
web/vite.config.ts

该PR合并后不能正常工作，想要生效需要将用户的视频来源脱离配置文件管理，这将在后续的提交中逐步修改。

feat: 支持 webui 加载用户的订阅与收藏，一键点击订阅

---

Cargo.lock
Cargo.toml
crates/bili_sync/Cargo.toml
crates/bili_sync/src/api/auth.rs
crates/bili_sync/src/api/handler.rs
crates/bili_sync/src/api/wrapper.rs
crates/bili_sync/src/bilibili/analyzer.rs
crates/bili_sync/src/bilibili/client.rs
crates/bili_sync/src/bilibili/credential.rs
crates/bili_sync/src/bilibili/danmaku/canvas/mod.rs
crates/bili_sync/src/bilibili/me.rs
crates/bili_sync/src/config/current.rs
crates/bili_sync/src/config/flag.rs
crates/bili_sync/src/config/handlebar.rs
crates/bili_sync/src/config/item.rs
crates/bili_sync/src/config/legacy.rs
crates/bili_sync/src/config/mod.rs
crates/bili_sync/src/config/versioned_cache.rs
crates/bili_sync/src/config/versioned_config.rs
crates/bili_sync/src/task/mod.rs
crates/bili_sync/src/task/video_downloader.rs
web/src/lib/api.ts
web/src/lib/types.ts
web/src/routes/me/collections/+page.svelte
web/src/routes/me/favorites/+page.svelte
web/src/routes/me/uppers/+page.svelte
web/src/routes/settings/+page.svelte

另外：
1. 改良后端 Config 更新逻辑
2. 统一前后端的 ApiError 结构

feat: 支持前端编辑、提交 Config

---

crates/bili_sync/src/api/routes/mod.rs

浏览器创建 WebSocket 请求时如果指定了`Sec-WebSocket-Protocol`，那么服务器的响应也必须包含相同的`Sec-WebSocket-Protocol`。（close #394）
~~最开始我就是这样写的但用 Firefox 测试的时候发现不需要就删了，还得加回来 XD~~

fix: 修复 Chromium 系浏览器创建 WebSocket 失败的问题

---

docs/configuration.md

docs: 修复配置项描述

---

crates/bili_sync/src/database.rs
crates/bili_sync/src/main.rs

Changes: 
- Now the program will print error messages when the database initialization fails. It helps users and developers locate problems.

Add error messages for the case in which the database initialization fails

---

crates/bili_sync/src/workflow.rs

fix: 为填充视频详情添加并发限制，避免数据库竞争

---

crates/bili_sync/src/api/routes/config/mod.rs
crates/bili_sync/src/api/routes/dashboard/mod.rs
crates/bili_sync/src/api/routes/me/mod.rs
crates/bili_sync/src/api/routes/video_sources/mod.rs
crates/bili_sync/src/api/routes/videos/mod.rs
crates/bili_sync/src/database.rs
crates/bili_sync/src/main.rs
crates/bili_sync/src/task/http_server.rs
crates/bili_sync/src/task/video_downloader.rs

feat: sqlite 开启 Wal，移除不必要的 Arc，妥善释放数据库

---

Cargo.lock
Cargo.toml
crates/bili_sync/Cargo.toml
crates/bili_sync/src/bilibili/client.rs

使用 `ua_generator` 这个 crate 来随机生成 mac 下的 chrome 浏览器的 User-Agent

feat: 请求中header的User-Agent使用随机值
