Dockerfile
删除`tzdata`后使用`date`显示为UTC，安装后恢复`date`显示北京时间，故保留`tzdata`以确保日志时间正确
```
~ # date
Wed May  1 11:42:54 UTC 2024
~ # apk add tzdata
(1/1) Installing tzdata (2024a-r0)
OK: 130 MiB in 120 packages
~ # date
Wed May  1 19:43:00 CST 2024
```
=> Dockerfile - 保留tzdata

Cargo.lock, Cargo.toml, src/main.rs
=> chore: 使用 tracing 替换 env_logger

src/downloader.rs
=> fix: 修复当目标文件已存在时 ffmpeg 卡住的问题

README.md
=> Update README.md - compose中指定user，附加简要说明

entity/src/entities/page.rs, src/bilibili/video.rs
过去分页 cid 使用的类型是 i32，今天遇到了溢出的情况：
将 i32 修改为 i64 以修复该问题。
=> fix: 修复类型错误导致的数值溢出

crates/bili_sync/src/adapter/collection.rs
Pubtime 和 Favtime 在获取视频详情时会填充为相同的值，所以这个 bug 基本不会触发。
对于极少数的触发情况，也只会导致多请求一些 b 站接口，对程序正常运行不会有影响。
=> fix: 修复 exist_labels 可能判断错误的问题

Cargo.lock, Cargo.toml, crates/bili_sync/Cargo.toml, crates/bili_sync/src/adapter/collection.rs, crates/bili_sync/src/adapter/mod.rs, crates/bili_sync/src/bilibili/client.rs, crates/bili_sync/src/bilibili/collection.rs, crates/bili_sync/src/bilibili/credential.rs, crates/bili_sync/src/bilibili/mod.rs, crates/bili_sync/src/config.rs, crates/bili_sync/src/main.rs
还没测试，等本地测试一下再合。
同时发现上游的 rust 示例代码有不少问题，抽空给上游修一下（
=> feat: 为合集接口实现 wbi 签名

crates/bili_sync/src/adapter/collection.rs, crates/bili_sync/src/adapter/mod.rs, crates/bili_sync/src/bilibili/client.rs, crates/bili_sync/src/bilibili/collection.rs, crates/bili_sync/src/bilibili/credential.rs, crates/bili_sync/src/bilibili/mod.rs, crates/bili_sync/src/bilibili/video.rs, crates/bili_sync/src/main.rs
发现视频下载接口的风控也很可能是签名的问题，因此也给下载视频的接口加上签名。
1. 将 mixin key 提取为 static 变量，方便各个接口访问
2. 获取 mixin key 同样需要登录，因此直接复用 mixin key 接口，移除之前的 is_login
3. 调整 main 结构，避免每个 continue 前都写一遍 sleep
=> feat: 为下载视频接口加入 wbi 签名

Cargo.lock
=> build: 单独升级一下 time 依赖

Cargo.lock, Cargo.toml, crates/bili_sync/Cargo.toml, crates/bili_sync/src/adapter/helper/mod.rs, crates/bili_sync/src/utils/filenamify.rs, crates/bili_sync/src/utils/mod.rs, crates/bili_sync/src/workflow.rs
=> refactor: 将 filenamify 移动至本地，将正则表达式设置为 static

crates/bili_sync/src/bilibili/analyzer.rs
大部分是写法的重构，如：
1. 重构初学 rust 时写的笨比代码 `.is_xxx && .as_xxx.unwrap` 
2. 避免对常量数组使用 vec! 导致的堆分配，.to_string() 调用移动至过滤后
3. 程序仅需要获取 best_stream，使用 max_by() 代替 order_by().first() 以提升性能
此外，该 PR 还调整了流的排序逻辑，修复了两个问题：
1. hdr、dolby、hires 的流不受 min max quality 约束
2. 仅依赖 quality 枚举值大小导致的音频流排序错误
合并该 PR 后，应该能确保视频优先级顺序为：
```rust
// 没有特殊处理，按照优先级从低到高
pub enum VideoQuality {
Quality360p = 16,
Quality480p = 32,
Quality720p = 64,
Quality1080p = 80,
Quality1080pPLUS = 112,
Quality1080p60 = 116,
Quality4k = 120,
QualityHdr = 125,
QualityDolby = 126,
Quality8k = 127,
}
```
音频优先级顺序为：
```rust
// 排序时为 Dolby 和 HiRes 增加权重，实现 64k < 132k < 192k < Dolby < HiRes
pub enum AudioQuality {
Quality64k = 30216,
Quality132k = 30232,
QualityDolby = 30250,
QualityHiRES = 30251,
Quality192k = 30280,
}
```
待补充单元测试。
=> feat: 调整并重构视频音频流的选择逻辑，应该可以提升些许性能

crates/bili_sync/src/bilibili/analyzer.rs, crates/bili_sync/src/bilibili/collection.rs, crates/bili_sync/src/bilibili/credential.rs, crates/bili_sync/src/bilibili/mod.rs, crates/bili_sync/src/bilibili/submission.rs, crates/bili_sync/src/bilibili/video.rs, crates/bili_sync/src/config/global.rs, crates/bili_sync/src/config/mod.rs, crates/bili_sync/src/main.rs
=> refactor: 一些边边角角的小重构

crates/bili_sync/src/config/global.rs
仅在配置文件初始化时进行写入，并且要求用户修改配置文件后重新启动程序
=> fix:修改配置文件写入逻辑

crates/bili_sync/src/adapter/collection.rs, crates/bili_sync/src/adapter/favorite.rs, crates/bili_sync/src/adapter/helper/mod.rs, crates/bili_sync/src/adapter/mod.rs, crates/bili_sync/src/adapter/submission.rs, crates/bili_sync/src/adapter/watch_later.rs, crates/bili_sync/src/bilibili/mod.rs, crates/bili_sync/src/utils/convert.rs, crates/bili_sync/src/utils/mod.rs, crates/bili_sync/src/workflow.rs, crates/bili_sync_entity/src/entities/collection.rs, crates/bili_sync_entity/src/entities/favorite.rs, crates/bili_sync_entity/src/entities/submission.rs, crates/bili_sync_entity/src/entities/watch_later.rs, crates/bili_sync_migration/src/lib.rs, crates/bili_sync_migration/src/m20250122_062926_add_latest_row_at.rs
1. 从新到旧分页拉取视频（优先请求新视频）
2. 按照拉取顺序分批写入到数据库中（避免对象囤积，节省内存）
3. 当发现数据库中有“bvid、时间”重合的数据时认为到达了上次处理到的位置，中断任务（避免重复请求，减少请求次数）
当前的检测逻辑大多时候可以工作正常，但无法防御一些边缘情况，主要有两点。
请求第一页并写入到数据库的过程中，用户又收藏、更新了一条视频，这样第一页的最后一个视频被挤到了第二页的第一个。
这样在处理第二页时，会发现数据库中有“bvid、时间”重合的数据，错误触发了中断逻辑，导致后续的未处理视频丢失。
为了避免对象囤积节省内存，当前将视频写入数据库的顺序和接口的请求顺序是相同的，均为从新到旧。
如果有多页新视频，第一页请求成功且正确写入，第二页由于网络等原因请求错误，当前的处理逻辑是直接中断等待下次运行。
下次运行这个任务时，第一页这些较新的视频会触发中断逻辑，导致后续页面永久丢失，无法再处理。
不难看出当前问题在于检测逻辑**过于信任检测过程中产生的部分结果，导致对上次处理到的位置判断错误**，要解决这个问题需要维护一个在整个检测过程完成才更新的值。
因此该 PR 为所有的 video list 表引入了 `latest_row_at` 字段，记录了最后处理的视频时间，该字段会在新视频检测运行全部完成时被更新为最大的视频时间。
中断的唯一判断条件是当前处理到的视频时间 `<= latest_row_at`。
=> feat: 引入更健壮的新视频检测方法

crates/bili_sync/src/utils/nfo.rs
在简介开头添加了视频的原始外链，方便一键点击访问 b 站的原始视频：
=> feat: 将视频的原始 URL 放到简介中

Cargo.lock, Cargo.toml, crates/bili_sync/Cargo.toml, crates/bili_sync/src/downloader.rs
copy 内部维护固定 8kb 大小的缓冲区，而手动 for 循环的 bytes 会偶尔出现 4kb 乃至更小的数据包，更换后应该能少幅度减少写入频率。
=> refactor: 下载部分使用 tokio 的封装代替手动实现

crates/bili_sync/src/error.rs, crates/bili_sync/src/utils/status.rs, crates/bili_sync/src/workflow.rs
目前有两种错误会被忽略：文件权限问题导致的 PermissionDenied 与由网络波动引起的 error decoding response body。
=> feat: 在状态更新时忽略掉一些常见的错误

crates/bili_sync/src/error.rs, crates/bili_sync/src/task/video_downloader.rs, crates/bili_sync/src/workflow.rs
1. 使用 :# 来展示更加详细的错误信息
2. 常见的 error decode response body 可能是包裹在 io::Error::Custom 之中的，需要展开再匹配
=> chore: error 会打印更加详细的信息，修正常见错误的判断

crates/bili_sync/src/error.rs, crates/bili_sync/src/utils/status.rs, crates/bili_sync/src/workflow.rs
详见注释，除了能解决一般情况的分 p 下载状态标记不准确问题，还能修复分页返回 Ignored Error 时产生的逻辑错误。
=> fix: 修复 video 中分 p 下载状态的设置

crates/bili_sync/src/adapter/collection.rs, crates/bili_sync/src/adapter/mod.rs, crates/bili_sync/src/workflow.rs
详见 https://github.com/amtoaer/bili-sync/issues/289 中的讨论，不清楚 b 站视频合集/视频列表是怎样排序的，现有基于时间的提前 break 逻辑不能适用。
改成全量拉取保证程序正确性。
=> fix: 视频合集/视频列表改为全量拉取，确保正确更新

crates/bili_sync/src/adapter/collection.rs, crates/bili_sync/src/adapter/mod.rs, crates/bili_sync/src/workflow.rs
在上次的改动（#290）后，视频合集和视频列表在每次扫描时都会尝试 insert 所有视频，在发生冲突时忽略。虽然逻辑上正确，但这导致了很多无意义的数据库访问，可以通过优化 take_while 后续的 filter_map 逻辑来避免。
该修改应该可以显著改善视频列表/视频合集的扫描性能。
=> refactor: 调整视频列表/视频合集的扫描逻辑，优化性能

Cargo.lock, Cargo.toml, crates/bili_sync/Cargo.toml, crates/bili_sync/src/api/handler.rs, crates/bili_sync/src/api/request.rs, crates/bili_sync/src/api/response.rs, crates/bili_sync/src/task/http_server.rs, web/src/lib/api.ts, web/src/lib/components/status-editor.svelte, web/src/lib/types.ts, web/src/routes/video/[id]/+page.svelte
分析了一下，swagger-ui 在 release build 中引入了 10M+ 的二进制体积，有点太过头了。自己 fork 魔改了一下 [rust-embed-for-web](https://github.com/amtoaer/rust-embed-for-web) 和 [utoipa](https://github.com/amtoaer/utoipa)，支持了前端资源的 precompress。
这样一方面程序内需要嵌入的二进制文件减小了，另一方面由于浏览器支持 content encoding，后端不需要在托管时自行解压，而是可以直接传递 precompress 的文件并附加 content encoding 的 header，交由浏览器自动处理。
唯一的麻烦是有些前端资源（如 swagger-ui 的 swagger-initializer.js） 需要后端对 placeholder 进行替换后再展示，这种文件必须保留原始内容，否则压缩后 placeholder 就消失了。费了点事，给 rust-embed-for-web 添加了 preserve_source_except 搞了手曲线救国。
压缩算法选择的是 [brotli](https://developer.mozilla.org/en-US/docs/Glossary/Brotli_compression)，现代浏览器应该都已经在几年前做了支持，不会有明显兼容性问题。
实测修改后二进制体积由 26M 变为了 16M。
=> chore: 大幅缩减构建结果的二进制文件体积
